did: did:web:dome-iam.fiware.dev:did
jwkKid: 6f4c1255f4a54090bc8ff7365b13a9b7
# dfsdfsdfdfg
route:
  enabled: true
  host: dome-iam.fiware.dev
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  certificate:
    issuer:
      kind: ClusterIssuer
      name: letsencrypt-aws-prod

vcwaltid:
  deployment:
    image:  
      repository: waltid/ssikit
      tag: 1.2311262046.fix-didwebpath
      pullPolicy: Always
  api:
    core: 
      enabled: true
    auditor: 
      enabled: true
    signatory: 
      enabled: true
    custodian: 
      enabled: true
    essif: 
      enabled: true

  persistence: 
    enabled: true
    pvc:
      size: 1Gi

  templates:
    SomeService.json: |
      {
        "@context": ["https://www.w3.org/2018/credentials/v1"],
        "credentialSchema": {
          "id": "https://raw.githubusercontent.com/FIWARE-Ops/i4trust-provider/main/docs/schema.json",
          "type": "FullJsonSchemaValidator2021"
        },
        "credentialSubject": {
          "id": "did:ebsi:2AEMAqXWKYMu1JHPAgGcga4dxu7ThgfgN95VyJBJGZbSJUtp",
          "roles": [{
            "names": ["CREATE_ISSUER"],
            "target": "did:elsi:someservice"
          }]
        },
        "id": "urn:uuid:3add94f4-28ec-42a1-8704-4e4aa51006b4",
        "issued": "2021-08-31T00:00:00Z",
        "issuer": "did:ebsi:2A9BZ9SUe6BatacSpvs1V5CdjHvLpQ7bEsi2Jb6LdHKnQxaN",
        "validFrom": "2021-08-31T00:00:00Z",
        "issuanceDate": "2021-08-31T00:00:00Z",
        "type": ["VerifiableCredential", "SomeService"]
      }
    M2MTirCredential.json: |
      {
        "@context": [
          "https://www.w3.org/2018/credentials/v1"
        ],
        "credentialSubject": {
          "id": "did:ebsi:2AEMAqXWKYMu1JHPAgGcga4dxu7ThgfgN95VyJBJGZbSJUtp",
          "roles": [
            {
              "names": [
                "CREATE_ISSUER"
              ],
              "target": "did:web:somware.space"
            }
          ]
        },
        "id": "urn:uuid:3add94f4-28ec-42a1-8704-4e4aa51006b4",
        "issued": "2021-08-31T00:00:00Z",
        "issuer": "did:ebsi:2A9BZ9SUe6BatacSpvs1V5CdjHvLpQ7bEsi2Jb6LdHKnQxaN",
        "validFrom": "2021-08-31T00:00:00Z",
        "issuanceDate": "2021-08-31T00:00:00Z",
        "type": [
            "VerifiableCredential"
        ]
      }
